server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy for Finstat API
    location /finstat-api/ {
        rewrite ^/finstat-api/(.*)$ /$1 break;
        proxy_pass https://www.finstat.sk;
        proxy_set_header Host www.finstat.sk;
        proxy_set_header User-Agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
        proxy_set_header Accept 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8';
        proxy_set_header Accept-Language 'sk-SK,sk;q=0.9,en-US;q=0.8,en;q=0.7';
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }

    # Custom 404 page redirect to index for React Router
    error_page 404 /index.html;
}
